require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

RSpec/ImplicitExpect:
  EnforcedStyle: should

Style/Documentation:
  Enabled: false
  