require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

RSpec/ImplicitExpect:
  EnforcedStyle: should

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

Rails/StrongParametersExpect:
  Enabled: false
  